readable_terms = {
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura": " ",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ProducaoDeGraos": "Produção de Grãos",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#PragasEDoencas": "Pragas e Doenças",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#BaixaTemperatura": "Baixa Temperatura",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#MediaTemperatura": "Media Temperatura",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#AltaTemperatura": "Alta Temperatura",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Banana": "Banana",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Soja": "Soja",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Abacaxi": "Abacaxi",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Abobora": "Abóbora",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Alface": "Alface",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Argiloso": "Argiloso",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Arenoso": "Arenoso",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Calcario": "Calcarío",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#TipoDeSolo": "Tipo de Solo",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#EstresseHidrico": "Estressado Hídrico",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Seca": "Seca",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#CulturaPlantada": "Cultura Plantada",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#temDadosAgricolas": "tem dados agrícolas",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#DadosAgricolas": "Dados Agrícolas",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#UsoDeFertilizantes": "Uso de Fertilizantes",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ImpactoAgricola": "Impacto Agrícola",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Fungicidas": "Fungicidas",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ProducaoDeFrutas": "Produção de Frutas",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ProducaoDeLegumes": "Produção de Legumes",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#BaixaUmidade": "Baixa Umidade",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Inseticidas": "Inseticidas",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ChuvaIntensa": "Chuva Intensa",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Umidade": "Umidade",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Organico": "Organico",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#eDadosClimaticosDe": "é dados climáticos de",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Quimico": "Químico",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#eInfluenciaDe": "é influência de",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#AltaUmidade": "Alta Umidade",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#temDadosClimaticos": "tem dados climáticos",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ImpactoComNome": "Impacto Com Nome",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Temperatura": "Temperatura",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Herbicidas": "Herbicidas",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#DadosClimaticos": "Dados Climáticos",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#temInfluencia": "tem influência",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#temDadosClimaticos": "tem dados climáticos",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#Precipitacao": "Precipitação",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#UsoDeAgrotoxicos": "Uso de Agroquímicos",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ProblemasDeSolo": "Problemas de Solo",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#eDadosAgricolasDe": "é dados agrícolas de",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#ChuvaModerada": "Chuva Moderada",
    "http://www.semanticweb.org/sandr/ontologies/2025/0/OntoClimaAgricultura#MediaUmidade": "Média Umidade",

    "http://www.w3.org/2002/07/owl#equivalentClass": "é equivalente a", # Traduzindo o predicado
    "http://www.w3.org/2002/07/owl#someValuesFrom": "algum valor de",
    "http://www.w3.org/2002/07/owl#Restriction": "Restrição",
    "http://www.w3.org/2002/07/owl#onProperty": "de propriedade",
    "http://www.w3.org/2002/07/owl#hasValue": "tem valor",
    "http://www.w3.org/2000/01/rdf-schema#comment": "comentário",
    "http://www.w3.org/2000/01/rdf-schema#label": "rótulo",
    "http://www.w3.org/2002/07/owl#Class": "classe",
    "http://www.w3.org/2002/07/owl#inverseOf": "inverso de",
    "http://www.w3.org/2002/07/owl#AllDisjointClasses": "todas as classes disjuntas",
    "http://www.w3.org/2002/07/owl#complementOf": "complemento de",
    "http://www.w3.org/2002/07/owl#ObjectProperty": "propriedade de objeto",
    "http://www.w3.org/2002/07/owl#members": "membros",
    "http://www.w3.org/2002/07/owl#allValuesFrom": "todos os valores de",
    "http://www.w3.org/2002/07/owl#Ontology": "ontologia",
    "http://www.w3.org/2002/07/owl#intersectionOf": "interseção de",
    "http://www.w3.org/2002/07/owl#TransitiveProperty": "propriedade transitiva",
    "http://www.w3.org/2002/07/owl#versionIRI": "IRI da versão",
    "http://www.w3.org/2002/07/owl#FunctionalProperty": "propriedade funcional",
    "http://www.w3.org/2002/07/owl#Thing": "algo",
    "http://www.w3.org/2002/07/owl#unionOf": "união de",
    "http://www.w3.org/2002/07/owl#disjointWith": "disjunto com",

    "http://www.w3.org/2000/01/rdf-schema#subClassOf": "subclasse de",
    "http://www.w3.org/2000/01/rdf-schema#subPropertyOf": "subpropriedade de",
    "http://www.w3.org/2000/01/rdf-schema#range": "alcance",
    "http://www.w3.org/2000/01/rdf-schema#domain": "domínio",

    "http://www.w3.org/1999/02/22-rdf-syntax-ns#first": "primeiro",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "tipo",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": "resto",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil": "nulo",

}